### ISSUE TITLE
Tournament rules currently under development

### ISSUE THREAD

**Issue by panther2** [triplea-maps/world_war_ii_v5_1942#4]
On LH's pages setup modifications are discussed to balance the game for tournaments.

This modifications should be included into the map.

PR reflecting the up-to-date changes is here: #3 

@simon33-2 Could you please take a look and merge? Thank you!

**Comment by simon33-2** [comment]
I don't have merge access in v5. Only in global.

What are the changes BTW?

**Comment by panther2** [comment]
Ah, ok, never mind. 

So far the changes are:
```
Added UK-DD to Sea zone 7
Moved UK-Cruiser from Sea Zone 14 to Sea Zone 13
German Bomber in Germany moved to Ukraine
Remove 1 German sub from Sea Zone 5
Added 2 UK Infantry to India (Total now 5)
```
